let mapleader=" "

" -----Basic AutoCmd-----
" Fix tex file type set
autocmd BufRead,BufNewFile *.tex set filetype=tex

" Vertically center document when entering insert mode
autocmd InsertEnter * norm zz

" Remove trailing whitespace on save
autocmd BufWritePre * %s/\s\+$//e

" Alias replace all to S
nnoremap S :%s//gI<Left><Left><Left>

" Alias to duplicate line
nnoremap W :t.<Enter>

" Alias write and quit to Q
nnoremap <leader>q :wq<CR>
nnoremap <leader>w :w<CR>

" Disable folding
set nofoldenable

" Use the OS clipboard by default (on versions compiled with `+clipboard`)
set clipboard+=unnamedplus

" Enhance command-line completion
set wildmenu

" Add the g flag to search/replace by default
set nogdefault

" Don’t create backups when editing files in certain directories
set backupskip=/tmp/*,/private/tmp/*

" Enable line numbers
set number relativenumber

" Enable syntax highlighting
syntax on

" Highlight current line
set cursorline

" Copy indent from last line when starting new line
set autoindent

" Highlight searches
set hlsearch

" Ignore case of searches
set ignorecase
set smartcase

" Highlight dynamically as pattern is typed
set incsearch

" Enable mouse in all modes
set mouse=a

" Disable error bells
set noerrorbells

" Don’t reset cursor to start of line when moving around.
set nostartofline

" Show the cursor position
" set ruler

" Don’t show the intro message when starting Vim
set shortmess=atI

" Increase multi-key timeout
set timeout timeoutlen=3000 ttimeoutlen=100

" Autocompletion
set wildmode=longest,list,full

set expandtab
set shiftwidth=2
set softtabstop=2
set tabstop=2

" Cant set this because messes up colorscheme
" set termguicolors

call plug#begin(stdpath('data') . '/plugged')
Plug 'myusuf3/numbers.vim'
Plug 'lambdalisue/suda.vim'
Plug 'itchyny/lightline.vim'
Plug 'tpope/vim-commentary'
Plug 'dylanaraps/wal.vim'
Plug 'mboughaba/i3config.vim'
call plug#end()

" Enable smart edit suda.vim
let g:suda_smart_edit = 1

" Dont show the current mode
set noshowmode

" Detect filetypes
:filetype on

" Set pywal compatible color scheme
colorscheme wal

" Change line highlight color
highlight CursorLine ctermbg=0 ctermfg=None cterm=None
