#!/bin/sh

# Persist multi monitor layout
# https://github.com/wertarbyte/autorandr
autorandr --change --force &

# Set keyboard auto repeat rate
#xset r rate 300 50 &

# Make screen blank after 15min
xset dpms 0 0 900 &

# Fix cursor
xsetroot -cursor_name left_ptr &

# Launch i3 with dbus-launch because of flameshot
dbus-launch /usr/bin/i3
#bspwm
