#!/bin/sh

# Tell i3 which terminal we want to use
export TERMINAL="kitty"

# Allow i3 to execute our custom scripts
export PATH=$HOME/.local/bin:$PATH

# Persist multi monitor layout
# https://github.com/wertarbyte/autorandr
autorandr --change --force &

# Set keyboard auto repeat rate
xset r rate 260 10

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

# Make screen blank after 15min
xset dpms 0 0 900

# Map capslock to escape
setxkbmap -option "caps:escape"

# Fix cursor
xsetroot -cursor_name left_ptr &

# Enable numlock
numlockx &

# Restore wal (pywal) colors scheme
wal -R

# Run polkit-mate-authentication-agent-1 for polkit
#/usr/libexec/polkit-mate-authentication-agent-1 &

# Launch i3 with dbus-launch because of flameshot
exec dbus-launch /usr/bin/i3
