export GPG_TTY="$( tty )"

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Restore wpg colors for terminal
[[ ! -f $HOME/.config/wpg/sequences ]] || (cat $HOME/.config/wpg/sequences &)

export ZDOTDIR=~/.zsh

### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing DHARMA Initiative Plugin Manager (zdharma/zinit)…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"

autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zinit-zsh/z-a-patch-dl \
    zinit-zsh/z-a-as-monitor \
    zinit-zsh/z-a-bin-gem-node

# Git aliases
zinit ice svn; zinit snippet PZT::modules/git

# DNF aliases
zinit snippet OMZ::plugins/dnf/dnf.plugin.zsh

# Systemd aliases
zinit snippet OMZ::plugins/systemd/systemd.plugin.zsh

# Extract aliases
zinit snippet OMZ::plugins/extract/extract.plugin.zsh

# z fast navigation
zinit snippet https://github.com/agkozak/zsh-z/blob/master/zsh-z.plugin.zsh

# docker completion
zinit ice as"completion"
zinit snippet https://github.com/docker/cli/blob/master/contrib/completion/zsh/_docker

# Help remembering aliases
zinit light djui/alias-tips

# Introduce a new ctrl+r
zinit light zdharma/history-search-multi-word

# Prompt
zinit ice depth=1; zinit light romkatv/powerlevel10k

# Best combination
zinit wait lucid for \
 atinit"ZINIT[COMPINIT_OPTS]=-C; zicompinit; zicdreplay" \
    zdharma/fast-syntax-highlighting \
 blockf \
    zsh-users/zsh-completions \
 atload"!_zsh_autosuggest_start" \
    zsh-users/zsh-autosuggestions

# Local local files
zpl ice atinit'local i; for i in *; do source $i; done'; zpl light $ZDOTDIR/config

# To customize prompt, run `p10k configure` or edit ~/.zsh/.p10k.zsh.
[[ ! -f ${ZDOTDIR}/.p10k.zsh ]] || source ${ZDOTDIR}/.p10k.zsh

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/fuhrmann/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/home/fuhrmann/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/fuhrmann/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/fuhrmann/Downloads/google-cloud-sdk/completion.zsh.inc'; fi
