source $HOME/.exports
source /usr/share/antigen.zsh

# Initialize antigen plugin manager
antigen init $HOME/.antigenrc

# Import colorscheme from 'wal' asynchronously
# &   # Run the process in the background.
# ( ) # Hide shell job control messages.
(cat ~/.cache/wal/sequences &)

# To add support for TTYs this line can be optionally added.
[ -f $HOME/.cache/wal/colors-tty.sh ] && source $HOME/.cache/wal/colors-tty.sh

source $HOME/.aliases

# when completing from the middle of a word, move the cursor to the end of the word    
setopt always_to_end

# append
setopt append_history     

# Remove older duplicate entries from history 
setopt hist_ignore_all_dups

# trim blanks
setopt hist_reduce_blanks

# show before executing history commands
setopt hist_verify

# add commands as they are typed, don't wait until shell exit 
setopt inc_append_history

# self explicit
setopt auto_remove_slash

# resolve symlinks
setopt chase_links         

# activate complex pattern globbing
setopt extended_glob

# include dotfiles in globbing
setopt glob_dots

# no bell on error
unsetopt beep

# no bell on error in history
unsetopt hist_beep

# ask for confirmation for `rm *' or `rm path/*'
unsetopt rm_star_silent
