#! /bin/sh


. "$HOME/.cache/wal/colors.sh" &

. "$HOME/.controller_config" &

pgrep -x sxhkd > /dev/null || sxhkd &

launchpolybar &

# Fix for spotify
wmname LG3D &

/usr/libexec/polkit-mate-authentication-agent-1f &

pactl set-default-sink alsa_output.pci-0000_01_00.1.hdmi-stereo &&
pactl set-default-source alsa_output.pci-0000_01_00.1.hdmi-stereo.monitor &&
pactl set-card-profile alsa_card.pci-0000_01_00.1 output:hdmi-stereo &

## BSPWM
bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config focused_border_color $color3
bspc config presel_feedback_color $color6

bspc config external_rules_command     ~/.config/bspwm/bspwm-rules.sh
bspc config automatic_scheme 	       alternate
bspc config initial_polarity           second_child
bspc config remove_disabled_monitors   true
bspc config remove_unplugged_monitors  true
bspc config merge_overlapping_monitors true

bspc config split_ratio                0.65
bspc config borderless_monocle         true
bspc config gapless_monocle            true
bspc config single_monocle             true
bspc config presel_feedback 	       true
bspc config bottom_padding 	           0
bspc config left_padding 		       0
bspc config right_padding              0
bspc config border_width               2
bspc config window_gap                 0

bspc rule -a Steam state=tiled desktop=^9
bspc rule -a steam:steam state=floating floating=on focus=off border=off layer=normal