#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
killall bspswallow
pidof bspswallow || bspswallow &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config automatic_scheme 	 alternate
bspc config initial_polarity     second_child

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config split_ratio          0.65
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config presel_feedback 	 true

bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 10


bspc rule -a Chrome desktop='^2'
bspc rule -a Wpg state=floating center=on rectangle='600x600+0+0'
