#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
launchpolybar &
wmname LG3D &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config external_rules_command ~/.config/bspwm/bspwm-rules.sh
bspc config automatic_scheme 	 alternate
bspc config initial_polarity     second_child
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true
bspc config split_ratio          0.65
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config presel_feedback 	 true
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 0