config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_ssh:
    src: ssh
    dst: ~/.ssh
    link: link
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
    link: link
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
    link: link
  f_gitignore:
    src: gitignore
    dst: ~/.gitignore
    link: link
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
    link: link
  f_bash_profile:
    src: bash_profile
    dst: ~/.bash_profile
    link: link
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
    link: link
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
    link: link
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
    link: link
  d_ranger:
    src: config/ranger
    dst: ~/.config/ranger
    link: link
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
    link: link
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
    link: link
  d_i3:
    src: config/i3
    dst: ~/.config/i3
    link: link
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
    link: link
  d_zathura:
    src: config/zathura
    dst: ~/.config/zathura
    link: link
  d_ncspot:
    src: config/ncspot
    dst: ~/.config/ncspot
    link: link_children
  f_redshift.conf:
    src: config/redshift.conf
    dst: ~/.config/redshift.conf
    link: link
  f_keyledsd.conf:
    src: config/keyledsd.conf
    dst: ~/.config/keyledsd.conf
    link: link
  d_vis:
    src: config/vis
    dst: ~/.config/vis
    link: link_children
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
    link: link_children
  f_mpd.conf:
    src: config/mpd/mpd.conf
    dst: ~/.config/mpd/mpd.conf
    link: link
  f_config:
    src: config/ncmpcpp/config
    dst: ~/.config/ncmpcpp/config
    link: link
  f_config.conf:
    src: config/neofetch/config.conf
    dst: ~/.config/neofetch/config.conf
    link: link
  f_mpdris2.conf:
    src: config/mpDris2/mpDris2.conf
    dst: ~/.config/mpDris2/mpDris2.conf
    link: link
  f_htoprc:
    src: config/htop/htoprc
    dst: ~/.config/htop/htoprc
    link: link
  d_bin:
    src: local/bin
    dst: ~/.local/bin
    link: link
  f_user-dirs.dirs:
    src: config/user-dirs.dirs
    dst: ~/.config/user-dirs.dirs
    link: link
  f_user-dirs.locale:
    src: config/user-dirs.locale
    dst: ~/.config/user-dirs.locale
    link: link
  f_transmission.service:
    src: config/systemd/user/transmission.service
    dst: ~/.config/systemd/user/transmission.service
    link: link
  f_keyledsd.service:
    src: config/systemd/user/keyledsd.service
    dst: ~/.config/systemd/user/keyledsd.service
    link: link
  d_config:
    src: zsh/config
    dst: ~/.zsh/config
    link: link
  f_p10k.zsh:
    src: zsh/.p10k.zsh
    dst: ~/.zsh/.p10k.zsh
    link: link
  f_xclients:
    src: Xclients
    dst: ~/.Xclients
    link: link
  f_zprofile:
    src: zprofile
    dst: ~/.zprofile
    link: link
  f_profile:
    src: profile
    dst: ~/.profile
    link: link
  f_flameshot.ini:
    src: config/Dharkael/flameshot.ini
    dst: ~/.config/Dharkael/flameshot.ini
    link: link
  f_dunstrc:
    src: config/dunst/dunstrc
    dst: ~/.config/dunst/dunstrc
    link: link
  f_settings.json:
    src: config/transmission-daemon/settings.json
    dst: ~/.config/transmission-daemon/settings.json
    link: link
  d_wpg:
    src: config/wpg
    dst: ~/.config/wpg
    link: link
  d_fonts:
    src: local/share/fonts
    dst: ~/.local/share/fonts
    link: link
  f_lscolors.sh:
    src: local/share/lscolors.sh
    dst: ~/.local/share/lscolors.sh
    link: link
  f_borg-backup.service:
    src: config/systemd/user/borg-backup.service
    dst: ~/.config/systemd/user/borg-backup.service
    link: link
  f_borg-backup.timer:
    src: config/systemd/user/borg-backup.timer
    dst: ~/.config/systemd/user/borg-backup.timer
    link: link
  d_flatcolor:
    src: local/share/themes/FlatColor
    dst: ~/.local/share/themes/FlatColor
    link: link
  f_mpris-scrobbler.desktop:
    src: config/autostart/mpris-scrobbler.desktop
    dst: ~/.config/autostart/mpris-scrobbler.desktop
    link: link
  d_plex:
    src: apps/docker/plex
    dst: ~/apps/docker/plex
    link: link
  d_sabnzbd:
    src: apps/docker/sabnzbd
    dst: ~/apps/docker/sabnzbd
    link: link
  d_sonarr:
    src: apps/docker/sonarr
    dst: ~/apps/docker/sonarr
    link: link
  d_caddy2:
    src: apps/docker/caddy2
    dst: ~/apps/docker/caddy2
    link: link
  d_sxhkd:
    src: config/sxhkd
    dst: ~/.config/sxhkd
    link: link
  d_bspwm:
    src: config/bspwm
    dst: ~/.config/bspwm
    link: link
profiles:
  fridora:
    dotfiles:
    - d_ssh
    - f_zshrc
    - f_gitconfig
    - f_gitignore
    - d_rofi
    - f_bash_profile
    - f_vimrc
    - f_xresources
    - f_bashrc
    - d_ranger
    - d_polybar
    - d_nvim
    - d_i3
    - d_alacritty
    - d_zathura
    - d_ncspot
    - f_redshift.conf
    - f_keyledsd.conf
    - d_vis
    - d_kitty
    - f_mpd.conf
    - f_config
    - f_config.conf
    - f_mpdris2.conf
    - f_htoprc
    - d_bin
    - f_user-dirs.dirs
    - f_user-dirs.locale
    - f_transmission.service
    - f_keyledsd.service
    - d_config
    - f_p10k.zsh
    - f_xclients
    - f_zprofile
    - f_profile
    - f_flameshot.ini
    - f_dunstrc
    - f_settings.json
    - d_wpg
    - d_fonts
    - f_lscolors.sh
    - f_borg-backup.service
    - f_borg-backup.timer
    - d_flatcolor
    - f_mpris-scrobbler.desktop
    - d_plex
    - d_sabnzbd
    - d_sonarr
    - d_caddy2
    - d_sxhkd
    - d_bspwm
