---
version: '3.7'

services:
  qmk:
    image: qmkfm/qmk_firmware
    privileged: true
    volumes:
      - /dev:/dev
      - ./:/qmk_firmware/keyboards/massdrop/alt/keymaps/custom
      - ./.build/:/qmk_firmware/.build
    command: "make massdrop/alt:custom"
