version: "2.1"

networks:
  traefik:
    external: true

services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    networks:
      - traefik
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Campo_Grande
      - UMASK_SET=022 #optional
    volumes:
      - /disks/Documentos/Apps/sonarr:/config
      - /disks/Seriados:/tv
      - /disks/Documentos/Downloads/sabnzbd:/downloads
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.rule=Host(`sonarr.localhost.dev`)
      - traefik.http.routers.sonarr.tls=true
      - traefik.http.routers.sonarr.entrypoints=http,https
      - traefik.port=8989
    expose:
      - 8989
    restart: unless-stopped
