version: "2.1"

networks:
  proxy:
    external: true

services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Campo_Grande
      - UMASK_SET=022 #optional
    volumes:
      - /disks/Documentos/Apps/sonarr:/config
      - /disks/Seriados:/tv
      - /disks/Documentos/Downloads/sabnzbd:/downloads
    expose:
      - 8989
    restart: unless-stopped
