version: "2.1"

networks:
  proxy:
    external: true

services:
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Campo_Grande
    volumes:
      - /disks/Documentos/Apps/sabnzbd:/config
      - /disks/Documentos/Downloads/sabnzbd:/downloads
    restart: unless-stopped
