version: "2.1"

networks:
  traefik:
    external: true

services:
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    networks:
      - traefik
    #network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Campo_Grande
    volumes:
      - /disks/Documentos/Apps/sabnzbd:/config
      - /disks/Documentos/Downloads/sabnzbd:/downloads
    labels:
      - traefik.enable=true
      - traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.localhost`)
      - traefik.http.routers.sabnzbd.entrypoints=http
      - traefik.port=8080
    restart: unless-stopped
