#!/bin/env bash

count=$(pgrep ncspot)
if [ "$count" -eq 1 ]; then
    kitty --class music --session "$HOME"/projetos/dotfiles/dotfiles/config/kitty/ncspot-session.kitty
else
    i3-msg "[class=music] focus"
fi
