---
version: "2.1"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022
    volumes:
      - /disks/Documentos/Plex:/config
      - /disks/Seriados:/tv
      - /disks/Filmes:/movies
      - /disks/Documentos/Musicas:/musics
    restart: unless-stopped
