version: "2.1"

networks:
  traefik:
    external: true

services:
  plex:
    image: linuxserver/plex
    container_name: plex
    networks:
      - traefik
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022
    volumes:
      - /disks/Documentos/Plex:/config
      - /disks/Seriados:/tv
      - /disks/Filmes:/movies
      - /disks/Documentos/Musicas:/musics
    labels:
      - traefik.enable=true
      - traefik.http.routers.plex.rule=Host(`plex.localhost`)
      - traefik.http.routers.plex.entrypoints=http
      - traefik.http.services.plex.loadbalancer.server.port=32400
    expose:
      - 32400
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    restart: unless-stopped
