#!/bin/bash
selected=$1
cwd=$(echo $(dirname $0))
config_file=$HOME/.config/rofi/tasks.json
tasks=$(cat $config_file)

if [ -z "${selected}" ]; then
	echo $tasks | jq -j 'map(.name) | join("\n")' 
	exit 0
else
	task=$(echo $tasks | jq ".[] | select(.name == \"$selected\")")

	# Exit if no task was found
	if [[ $task == "" ]]; then
	  echo "No task defined as '$selected' within config file."
	  exit 1
	fi

	task_command=$(echo $task | jq ".command")
	confirm=$(echo $task | jq ".confirm")

	# Check whether we need confirmation to run this task
	if [[ $confirm == "true" ]]; then
	  # Chain the confirm command before executing the selected command
	  confirm_script="$cwd/confirm.sh 'Confirm $selected?'"
	  pkill -TERM rofi && eval "$confirm_script && \"$task_command\" > /dev/null &"
	else
	  pkill -TERM rofi && eval "\"$task_command\" > /dev/null &"
	fi
fi